"""Signal engine: turn momentum scores into confirmed trade candidates.

Each strategy has its own SignalEngine with its own thresholds, so the same
score stream can produce different candidates per methodology.

Three independent gates run per candidate, and a symbol's tier decides which
apply:

  social     unusual attention from enough distinct, bullish accounts
  trend      price above its moving average with volume participation
  direction  positive trailing return over the strategy's confirmation window

  tier mode | social | trend | direction
  ----------+--------+-------+----------
  social    |  yes   |  no   |   yes      micro caps: attention leads price
  hybrid    |  yes   |  yes  |   yes      mid caps: both must agree
  trend     |  no    |  yes  |   yes      majors: attention is weak/contrarian

Direction always applies. Buying an attention spike generated by a crash is the
single most damaging failure mode of a pure mention-count signal.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..config import (
    MarketConfig,
    SignalsConfig,
    StrategyConfig,
    TierConfig,
    UniverseConfig,
    get_market,
    get_signals,
)
from ..logging_setup import get_logger
from ..market import MarketData, TechnicalSnapshot
from ..scorer import ScoreResult

log = get_logger("smt.signals")


@dataclass(frozen=True)
class GateResult:
    """Outcome of one entry gate.

    `evaluated` is False when the gate could not run at all (no market data, or
    the gate is switched off). A mode that depends on a gate must not trade when
    that gate never ran, regardless of the `passed` default.
    """

    passed: bool
    why: str
    evaluated: bool = True


@dataclass
class TradeCandidate:
    ticker: str
    product_id: str
    zscore: float
    mentions: int
    sources: int
    reason: str
    strategy: str = "intraday"
    authors: int = 0
    bullish_ratio: float = 0.0
    tier: str = "mid"
    atr_pct: float = 0.0
    trailing_return: float = 0.0


class SignalEngine:
    """Applies one strategy's entry thresholds plus tiered confirmation.

    `market` is optional: without it the price gates cannot be evaluated and are
    skipped, which keeps unit tests focused on social logic. The runner always
    supplies one, so production entries are always price-confirmed.
    """

    def __init__(
        self,
        strategy: StrategyConfig,
        universe: UniverseConfig,
        signals: SignalsConfig | None = None,
        market: MarketData | None = None,
        market_cfg: MarketConfig | None = None,
    ):
        self.strategy = strategy
        self.universe = universe
        self.signals = signals if signals is not None else get_signals()
        self.market = market
        self.market_cfg = market_cfg if market_cfg is not None else get_market()

    # ---- Gates --------------------------------------------------------------

    def _social_ok(self, s: ScoreResult, tier: TierConfig) -> GateResult:
        st = self.strategy
        min_z = st.signal_min_zscore * tier.zscore_mult
        if s.zscore < min_z:
            return GateResult(False, f"z={s.zscore:.2f} < {min_z:.2f}")

        min_mentions = st.signal_min_mentions * tier.min_mentions_mult
        if s.mentions_window < min_mentions:
            return GateResult(False, f"mentions={s.mentions_window} < {min_mentions:.0f}")

        if s.distinct_sources < st.signal_min_distinct_sources:
            return GateResult(
                False, f"sources={s.distinct_sources} < {st.signal_min_distinct_sources}"
            )

        if s.distinct_authors < st.signal_min_distinct_authors:
            return GateResult(
                False, f"authors={s.distinct_authors} < {st.signal_min_distinct_authors}"
            )

        # Only judge polarity once enough posts carry directional language;
        # below that the ratio is too noisy to gate on.
        enough_polarity = s.directional_posts >= self.signals.min_sentiment_posts
        if enough_polarity and s.bullish_ratio < st.signal_min_bullish_ratio:
            return GateResult(
                False,
                f"bullish={s.bullish_ratio:.0%} < {st.signal_min_bullish_ratio:.0%} "
                f"({s.directional_posts} directional posts)",
            )

        return GateResult(True, "social confirmed")

    def _trend_ok(self, snap: TechnicalSnapshot | None) -> GateResult:
        conf = self.market_cfg.confirmation
        if snap is None or not conf.enabled:
            return GateResult(True, "trend gate not evaluated", evaluated=False)
        if not snap.ok:
            return GateResult(
                not conf.fail_closed, f"no market data ({snap.detail})", evaluated=False
            )

        if conf.require_above_sma and not snap.above_sma:
            return GateResult(
                False, f"price {snap.price:.6f} below SMA{conf.sma_periods} {snap.sma:.6f}"
            )

        if snap.volume_z < conf.min_volume_zscore:
            return GateResult(
                False, f"volume z={snap.volume_z:.2f} < {conf.min_volume_zscore:.2f}"
            )

        return GateResult(True, "trend confirmed")

    def _direction_ok(self, snap: TechnicalSnapshot | None, tier: TierConfig) -> GateResult:
        conf = self.market_cfg.confirmation
        if snap is None or not conf.enabled or not conf.require_positive_return:
            return GateResult(True, "direction gate not evaluated", evaluated=False)
        if not snap.ok:
            return GateResult(
                not conf.fail_closed, f"no market data ({snap.detail})", evaluated=False
            )

        floor = max(self.strategy.confirm_min_return_pct, tier.min_trailing_return_pct)
        if snap.trailing_return < floor:
            return GateResult(
                False,
                f"{self.strategy.confirm_lookback_hours}h return "
                f"{snap.trailing_return:.2%} < {floor:.2%}",
            )
        return GateResult(
            True, f"{self.strategy.confirm_lookback_hours}h return {snap.trailing_return:.2%}"
        )

    # ---- Market plumbing ----------------------------------------------------

    def _snapshot(self, product_id: str) -> TechnicalSnapshot | None:
        if self.market is None:
            return None
        granularity = self.market_cfg.candle_granularity_seconds
        periods = max(1, (self.strategy.confirm_lookback_hours * 3600) // granularity)
        return self.market.snapshot(
            product_id,
            sma_periods=self.market_cfg.confirmation.sma_periods,
            lookback_periods=periods,
        )

    def _regime(self) -> tuple[bool, str]:
        if self.market is None:
            return True, "regime not evaluated"
        return self.market.regime_ok()

    # ---- Entry point --------------------------------------------------------

    def candidates(self, scores: list[ScoreResult]) -> list[TradeCandidate]:
        regime_ok, regime_detail = self._regime()
        if not regime_ok:
            log.info("[%s] regime gate: no new entries (%s)", self.strategy.name, regime_detail)
            return []

        out: list[TradeCandidate] = []
        for s in scores:
            cand = self._evaluate(s)
            if cand is not None:
                out.append(cand)
        return out

    def _evaluate(self, s: ScoreResult) -> TradeCandidate | None:
        if not self.universe.tradeable(s.ticker):
            return None

        st = self.strategy
        tier_name = self.universe.tier_of(s.ticker, self.signals.default_tier)
        tier = self.signals.tier(tier_name)
        spec = self.universe.symbols[s.ticker]

        needs_social = tier.signal_mode in ("social", "hybrid")
        needs_trend = tier.signal_mode in ("trend", "hybrid")

        social = GateResult(True, "social gate skipped", evaluated=False)
        if needs_social:
            social = self._social_ok(s, tier)
            if not social.passed:
                # Quiet by default: most symbols fail this on most polls.
                log.debug("[%s] %s rejected: %s", st.name, s.ticker, social.why)
                return None

        snap = self._snapshot(spec.product_id)

        if needs_trend:
            trend = self._trend_ok(snap)
            # In trend mode price IS the signal. If the gate never ran there is
            # no evidence at all, so never fall through to an entry.
            if not trend.passed or (tier.signal_mode == "trend" and not trend.evaluated):
                log.info("[%s] %s blocked by trend gate: %s", st.name, s.ticker, trend.why)
                return None

        direction = self._direction_ok(snap, tier)
        if not direction.passed:
            log.info("[%s] %s blocked by direction gate: %s", st.name, s.ticker, direction.why)
            return None

        reason = f"[{tier_name}/{tier.signal_mode}] {social.why}; {direction.why}"
        log.info(
            "SIGNAL[%s] %s tier=%s mode=%s z=%.2f mentions=%d authors=%d bullish=%.0f%%",
            st.name,
            s.ticker,
            tier_name,
            tier.signal_mode,
            s.zscore,
            s.mentions_window,
            s.distinct_authors,
            s.bullish_ratio * 100,
        )
        return TradeCandidate(
            ticker=s.ticker,
            product_id=spec.product_id,
            zscore=s.zscore,
            mentions=s.mentions_window,
            sources=s.distinct_sources,
            reason=reason,
            strategy=st.name,
            authors=s.distinct_authors,
            bullish_ratio=s.bullish_ratio,
            tier=tier_name,
            atr_pct=snap.atr_pct if snap and snap.ok else 0.0,
            trailing_return=snap.trailing_return if snap and snap.ok else 0.0,
        )
